= Vector Spaces
:sectnums:
:stem: latexmath  

== 용어

* complex vector space (복소 벡터 공간): scalar가 복소수일 때

* homogeneous linear system: stem:[A\mathbf{x} = \mathbf{y}]가 아닌, stem:[A\mathbf{x} =
  \mathbf{0}] 형태의 연립 방정식

* kernel(핵, = null space)

* Null Space: stem:[A\mathbf{x} = \mathbf{0}]에서 벡터 stem:[\mathbf{x}]가 이루는 공간을 의미

* Column Space: stem:[A\mathbf{x} = \mathbf{y}]에서 stem:[\mathbf{y}]가 이루는 공간을 의미



== 표기

* stem:[V]: vector space

* stem:[\mathbb{S}]: signal vector

* stem:[\mathrm{Nul}\,\, A] (null space of the matrix stem:[A]): stem:[A\mathbf{x} =
  \mathbf{0}]을 만드는 벡터 stem:[\mathbf{x}]


== Column Space

=== Column Space of matrix stem:[A]

* 행렬 stem:[A]는 column vercor들로 구성된다. 이 column vector들이 형성하는, 모든 벡터들의
  집합(= span of column vectors)을 column space라고 한다.

* stem:[\mathrm{Col}\, (A) = \{ \mathbf{v_1}, \mathbf{v_2}, \cdots \mathbf{v_3} \} =
        \mathrm{Span}\, (\mathbf{v_1}, \mathbf{v_2}, \cdots \mathbf{v_3}) ]

=== Null Space of matrix stem:[A]

* stem:[A \mathbf{x} = \mathbf{0}]를 만족시키는 stem:[\mathbf{x}]를 행렬 stem:[A]의 Null
  Space라고 한다.

* 행렬 stem:[A]를 이루는 모든 column vercor들이 선형 독립이면, stem:[ \mathrm{Nul}\, (A) =
  \{\mathbf{0}\} ]이다.
                                                                                            
