= Chapter 2. Matrix Algebra
:sectnums:
:stem: latexmath  


.용어 설명
[sidebar]
****
sparse matrix(희소 행렬)::
행렬의 값이 대부분 0인 행렬이다.

partitioned matrix or block matrix(분할 행렬)::
하나의 행렬은 더 작은 부분 행렬(submatrix)로 분할될 수 있다.

matrix factorization(행렬의 분해)::
LU factorization

diagonal matrix(대각 행렬)::
정사 행렬 중에, 주 대각 성분(main diagonal entry)들을 제외한 모든 성분이 0인 행렬.

transposed matrix(전치 행렬)::
행렬의 행과 열이 뒤바뀐 행렬

singular matrix(특이 행렬)::
역행렬이 존재하지 않는 행렬

nonsingular matrix(정칙 행렬)::
역행렬이 존재하는 행렬

elementary matrix(기본 행렬)::
기본 행렬은 단위행렬에 기본행 연산(elementary row operation)을 한 번 실행하여 얻어지는
행렬이다.
****


== Matrix Operations

[sidebar]
****
* 행렬간 덧셈: matrix + matrix
* 행렬의 실수배: matrix * 실수배
* 행렬간 곱셈: matrix * matrix
* 행렬간 곱셈의 성질
* 전치 행렬
* 전치행렬의 성질
****


== The Inverse of Matrix

[sidebar]
****
* 역행렬의 정의
* 역행렬 구하는 공식
* 역행렬의 성질
* 기본 행렬(elementary matrix)
* 기본행 연산(elementary row operation)
****

=== 역행렬

역행렬은 정사 행렬(square matrix)인 경우에만 가능하다.

inverse matrix(역행렬)::
[stem]
++++
A^{-1} = \frac{1}{ad-bc} \begin{bmatrix} \hfil d & -b \\ -c & \hfil a \end{bmatrix}
++++


determinant(행렬식)::
stem:[\det A = ad-bc]


=== 기본 행렬

elementary matrix(기본 행렬)::
기본 행렬은 단위 행렬에 기본행 연산(elementary row operation)을 한 번 실행하여 얻어지는
행렬이다.

기본행 연산::
기본행렬을 만드는 연산을 기본행 연산이라고 한다. 어떤 행렬에 기본행렬을 여러 번 곱하여
단위 행렬로 만들 수 있다면 그 행렬은 가역행렬 또는 역행렬이 존재함을 증명할 수 있고,
기본행 연산으로 가역행렬 또는 역행렬을 구할 수 있다.

=== 기본행 연산(elementary row operations)

기본행 연산법에는 3개의 방법이 있다.

. 두 행을 교환(Row switching transformations)
+
두 개의 행의 줄 전체를 아래 위로 교환한다.

. 한 행에 0이 아닌 상수를 곱함(Row-multiplying transformations)
+
행줄 전체에 0이 아닌 상수를 곱하여 행 전체에 n배를 한다.

. 한 행에 배수를 곱한 후, 이를 다른 행에 더함(Row-addition transformations)
+
한 행 전체에 n배를 하고 이 결과를 다시 다른 행에 더한다.


== Characteristics of Invertible Matrix

== Invertible Matrix Theorem

Let stem:[A] be a square stem:[n \times n] matrix. Then the following statements are
equivalent. That is, for a given stem:[A] , the statements are either all true or all
false.

* stem:[A] is an invertible matrix.
* stem:[A] is row equivalent to the stem:[n \times n] identity matrix.
* stem:[A] has stem:[n] pivot positions.
* The equation stem:[A {\bf x}={\bf 0}] has only the trivial solution.
* The columns of stem:[A] form a linearly independent set.
* The linear transformation stem:[\bf{x} \mapsto A\bf{x}] is one-to-one.
* The equation stem:[A {\bf x}=0] has at least one solution for each stem:[\bf{b}] in stem:[\mathbb{R}^n].
* The columns of stem:[A] span  stem:[\mathbb{R}^n].
* The linear transformation stem:[\bf{x} \mapsto A\bf{x}] onto stem:[\mathbb{R}^n].
* There is an stem:[n \times n] matrix stem:[C] such that stem:[CA = I].
* There is an stem:[n \times n] matrix stem:[D] such that stem:[AD = I].
* stem:[A^T] is an invertible matrix

[listing]
----
가우스 소거법을 통해 항등 행렬로 변환될 수 있는 행렬은 유일한 해를 갖는 연립방정식이다.

= 가역 행렬은 항등 행렬로 변환될 수 있다. 
----


== Partitioned Matriices

Row-Column Rule

[stem]
++++
\begin{bmatrix} a & b \\ c & d \\ e & f \end{bmatrix}
\begin{bmatrix} x \\ y \end{bmatrix}
= \begin{bmatrix} ax + by \\ cx + dy \\ ex + fy \end{bmatrix}
++++

Column-Row expansion of stem:[AB]

[stem]
++++
\begin{bmatrix} a \\ c \\ e \end{bmatrix}
\begin{bmatrix} x \end{bmatrix}
+
\begin{bmatrix} b \\ d \\ f \end{bmatrix}
\begin{bmatrix} y \end{bmatrix}
= \begin{bmatrix} ax + by \\ cx + dy \\ ex + fy \end{bmatrix}
++++




== Matrix Factorization

* matrix multiplication: stem:[AB = C] (일종의 곱셈 공식)
* matrix factorization:  stem:[C = AB] (일종의 인수 분해)


=== LU factorization (= LU Decomposition)

* L: unit Low triangular matrix
* U: Upper triangular matrix



== Leontiff Input-Output Model

[stem]
++++


\begin{eqnarray}
\mathbf{x}  &=& C\mathbf{x} + \mathbf{d} \\
I\mathbf{x} &=&  C\mathbf{x} + \mathbf{d} \\
(I-C)\mathbf{x} &=& \mathbf{d} \\
\mathbf{x}  &=& (I-C)^{-1} \mathbf{d} \\
            &=& (I + C + C^2 + \cdots + C^m) \mathbf{d}
\end{eqnarray}
++++

== APPLICATIONS TO COMPUTER GRAPHICS

* homogeneous coordiantes(동차 좌표)


== Subspaces of stem:[\mathbb{R}^n]

* subspace(부분 공간)


== Dimention and Rank

* dimention(차원)
* rank(차수)
* isomorphism(동형 사상)

=== 기저 벡터

* 기저 벡터 stem:[\mathcal{B}]
+
[stem]
++++
\mathcal{B} = \{ \mathbf{b}_1, \dots, \mathbf{b}_p \}
++++
+
기저 벡터 stem:[\mathcal{B}]는 벡터 stem:[ \mathbf{b}_1, ..., \mathbf{b}_p]로 이루어져 있음을
표현한다.

* stem:[\mathbf{x} \mapsto \begin{bmatrix} \mathbf{x} \end{bmatrix} _\mathcal{B}]
+
[stem]
++++
\begin{bmatrix} \mathbf{x} \end{bmatrix} _\mathcal{B}
= \begin{bmatrix} c_1 \\ \vdots \\ c_p \end{bmatrix}
= c_1 \mathbf{b}_1 + \dots + c_p \mathbf{b}_p
++++



벡터 stem:[\mathbf{x}]를, 기저 벡터 stem:[\mathcal{B}]를 기준으로 변환해 표현한 것.

