= Concepts
:sectnums:
:stem: latexmath  

== 선형대수의 핵심

선형대수의 핵심은 벡터의 합과 상수배(scalar multiplication) 연산이다.

After all, every topic in linear algebra is going to center around these two operations,
vector addition, and multiplication by numbers. Linear algebra topics tend to revolve
around these two fundamental operations: vector addition, and scalar multiplication;

The word "rank(차수)" means the number of dimensions in the output of a transformation.

== 행렬 방정식과 벡터 방정식

=== 행렬 방정식과 벡터 방정식의 관계

[stem]
++++
\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}
\begin{bmatrix} x \\ y \end{bmatrix}
=
\begin{bmatrix}
1 \cdot x + 0 \cdot y \\
0 \cdot x + 1 \cdot y
\end{bmatrix}
=
x \begin{bmatrix} 1 \\ 0 \end{bmatrix}
+ 
y \begin{bmatrix} 0 \\ 1 \end{bmatrix}
=
\begin{bmatrix} x \\ y \end{bmatrix}
++++

* 행렬 방정식: stem:[\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}
                    \begin{bmatrix} x \\ y \end{bmatrix}]

* 벡터 방정식: stem:[x \begin{bmatrix} 1 \\ 0 \end{bmatrix} + 
                     y \begin{bmatrix} 0 \\ 1 \end{bmatrix}]

* 열 벡터 stem:[\begin{bmatrix} 1 \\ 0 \end{bmatrix}]에 실수배 stem:[x]배한 결과를, 열
  벡터 stem:[\begin{bmatrix} 0 \\ 1 \end{bmatrix}]에 실수배 stem:[y]배한 결과에 더하면,
  벡터 stem:[\begin{bmatrix} x \\ y \end{bmatrix}]가 얻이진다.
+
  벡터의 덧셈 + 벡터의 실수배 = 선형 결합(linear combination)


=== 일반해

[stem]
++++
\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}
\begin{bmatrix} x \\ y \end{bmatrix}
=
\begin{bmatrix}
x \\ y
\end{bmatrix}
++++

임의의 좌표 stem:[(x, y)]를 입력하면, stem:[(x, y)] 출력이 나온다. 즉, 모든 평면 위의 점을
표현한다.


=== 특수해
 
[stem]
++++
\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}
\begin{bmatrix} 2 \\ 3 \end{bmatrix}
=
\begin{bmatrix}
2 \\ 3
\end{bmatrix}
++++

특정 좌표 stem:[(2, 3)]를 입력하면, 특정 값 stem:[(2, 3)] 출력이 나온다. 즉, 한 개의 점을
표현한다.

[stem]
++++
\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}
\begin{bmatrix} x \\ y \end{bmatrix}
=
\begin{bmatrix}
2 \\ 3
\end{bmatrix}
++++

위의 식을 만족하는 stem:[(x,y)]는 stem:[(2,3)] 한 개뿐이다.


== 행렬간 곱셈

* stem:[A = \begin{bmatrix} 2 & 3 \\ 1 & -5\end{bmatrix}],
  stem:[B = \begin{bmatrix} 4 & 3 & 6 \\ 1 & -2 & 3 \end{bmatrix}]

* stem:[{\bf b}_1 = \begin{bmatrix} 4 \\ 1 \end{bmatrix}],
  stem:[{\bf b}_2 = \begin{bmatrix} 3 \\ -2 \end{bmatrix}],
  stem:[{\bf b}_3 = \begin{bmatrix} 6 \\ 3 \end{bmatrix}]


* stem:[AB = \begin{bmatrix} 2 & 3 \\ 1 & -5\end{bmatrix}
             \begin{bmatrix} 4 & 3 & 6 \\ 1 & -2 & 3 \end{bmatrix}
           = \begin{bmatrix} A{\bf b}_1 & A{\bf b}_2 & A{\bf b}_3 \end{bmatrix} ]

* stem:[A{\bf b}_1 = \begin{bmatrix} 2 & 3 \\ 1 & -5\end{bmatrix}
                     \begin{bmatrix} 4 \\ 1 \end{bmatrix}
                   = \begin{bmatrix} 11 \\ -1 \end{bmatrix}],
+
stem:[A{\bf b}_2 = \begin{bmatrix} 2 & 3 \\ 1 & -5\end{bmatrix}
                   \begin{bmatrix} 3 \\ -2 \end{bmatrix}
                 = \begin{bmatrix} 0 \\ 13 \end{bmatrix}],
+
stem:[A{\bf b}_3 = \begin{bmatrix} 2 & 3 \\ 1 & -5\end{bmatrix}
                   \begin{bmatrix} 6 \\ 3 \end{bmatrix}
                 = \begin{bmatrix} 21 \\ -9 \end{bmatrix}]

* stem:[AB = \begin{bmatrix} 2 & 3 \\ 1 & -5\end{bmatrix}
             \begin{bmatrix} 4 & 3 & 6 \\ 1 & -2 & 3 \end{bmatrix}
           = \begin{bmatrix} 11 & 0 & 21 \\
                             -1 &13 & -9 \end{bmatrix}]

* 앞의 행렬 stem:[A]는 열벡터들을 모아 놓은 것이고, 뒤의 행렬 stem:[B]는 실수배들을 모아
  놓은 것이다.
